name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: mkdir build
      run: mkdir ./build
        
    - name: Deploy to AWS
      uses: reggionick/s3-deploy@v3
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.AWS_REGION }}
      
    - name: zip file
      run: |
        ls -al
        pwd
        cd build
        pwd
        ls
        cd ..
        cd ..
        pwd
        ls
        cd ..
        pwd
        ls
        
