name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.1] # 템플릿 기본값: [10.x, 12.x, 14.x]
        
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: backend Build
      run: |
        cd back_nestjs
        npm ci
        npm run build --if-present
        ls
        cd ..
        
    - name: front Build
      run: |
        cd front_nextjs
        npm ci
        npm run build --if-present
        cd ..
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
#     - name: Deploy to AWS
#       uses: reggionick/s3-deploy@v3
#       with:
#         bucket: ${{ secrets.S3_BUCKET }}
#         bucket-region: ${{ secrets.AWS_REGION }}
      
    - name: zip file
      run: |
        zip -r my-repo.zip ./back_nestjs/dist ./front_nextjs/dist ./scripts ./appspec.yml ./docker-compose.yaml
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./my-repo.zip s3://eno-codedeploydemobucket/
      
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name deploy-test
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name deploy-group
        --s3-location bucket=eno-codedeploydemobucket,bundleType=zip,key=my-repo.zip
